name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - Development
          - Test

jobs:
  build-and-deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ACR_NAME: ${{ vars.AZURE_ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.AZURE_ACR_NAME }}.azurecr.io
      ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      FRONTEND_NAME: ${{ vars.GTAA_PREFIX }}aca-uks-frontend
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}"
            }

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Api/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-frontend:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-frontend:latest

      - name: Check if Container App exists
        id: check_aca
        shell: bash
        run: |
          if az containerapp show --name "$FRONTEND_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Update Container App image and env
        if: steps.check_aca.outputs.exists == 'true'
        run: |
          az containerapp update \
            --name "FRONTEND_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --image "$ACR_LOGIN_SERVER/gtaa-frontend:${{ github.sha }}" \
            --set-env-vars \
              ASPNETCORE_ENVIRONMENT='${{ github.event.inputs.environment }}' \
              DOTNET_gcServer='1' \
              DOTNET_ReadyToRun='0' \
              WEBSITES_ENABLE_APP_SERVICE_STORAGE='false' \
            --registry-server "$ACR_LOGIN_SERVER" \
            --registry-username "$ACR_USERNAME" \
            --registry-password "$ACR_PASSWORD"