name: Deploy Apps

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - Development
          - Test
          - Production
      deploy_api:
        description: "Deploy the API"
        required: true
        type: boolean
        default: true
      deploy_admin:
        description: "Deploy the Admin"
        required: true
        type: boolean
        default: true
      deploy_frontend:
        description: "Deploy the Frontend"
        required: true
        type: boolean
        default: true

run-name: Deploy App(s) to ${{ github.event.inputs.environment || inputs.environment || 'Development' }}

jobs:
  prepare-infrastructure:
    name: "Prepare Infrastructure"
    uses: ./.github/workflows/azure-infrastructure.yml
    with:
      is_admin_deployment: ${{ github.event.inputs.deploy_admin == 'true' }}
      is_api_deployment: ${{ github.event.inputs.deploy_api == 'true' }}
      is_frontend_deployment: ${{ github.event.inputs.deploy_frontend == 'true' }}
      environment: ${{ github.event.inputs.environment || 'Development' }}
    secrets: inherit
    
  build-and-deploy-api:
    name: "Build & Deploy the Api"
    runs-on: ubuntu-latest
    needs: prepare-infrastructure
    if: ${{ github.event.inputs.deploy_api == 'true' }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ACR_NAME: ${{ vars.AZURE_ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.AZURE_ACR_NAME }}.azurecr.io
      ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      API_NAME: ${{ vars.GTAA_PREFIX }}app-uks-api
    environment: ${{ github.event.inputs.environment || 'Development' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}"
            }

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Api/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-api:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-api:latest

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --name "$API_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --slot "staging" \
            --settings \
              ASPNETCORE_ENVIRONMENT="${{ github.event.inputs.environment }}"

      - name: Update API App Service
        run: |
          az webapp config container set \
            --name "$API_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --slot "staging" \
            --docker-custom-image-name "$ACR_LOGIN_SERVER/gtaa-api:${{ github.sha }}" \
            --docker-registry-server-url "https://$ACR_LOGIN_SERVER" \
            --docker-registry-server-user "$ACR_USERNAME" \
            --docker-registry-server-password "$ACR_PASSWORD"

      - name: Swap staging to production
        run: |
          az webapp deployment slot swap \
            --resource-group "$RESOURCE_GROUP" \
            --name "$API_NAME" \
            --slot "staging" \
            --target-slot "production"

      - name: Delete staging slot
        run: |
          az webapp deployment slot delete \
            --resource-group "$RESOURCE_GROUP" \
            --name "$API_NAME" \
            --slot staging
  
  
  build-and-deploy-admin:
    name: "Build & Deploy the Admin"
    runs-on: ubuntu-latest
    needs: prepare-infrastructure
    if: ${{ github.event.inputs.deploy_admin == 'true' }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ACR_NAME: ${{ vars.AZURE_ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.AZURE_ACR_NAME }}.azurecr.io
      ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      ADMIN_NAME: ${{ vars.GTAA_PREFIX }}app-uks-admin
      ENVIRONMENT: ${{ github.event.inputs.environment || 'Development' }}
    environment: ${{ github.event.inputs.environment || 'Development' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}"
            }

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Admin/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-admin:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-admin:latest

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --name "$ADMIN_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --slot "staging" \
            --settings \
              ASPNETCORE_ENVIRONMENT="${{ github.event.inputs.environment }}"

      - name: Update API App Service
        run: |
          az webapp config container set \
            --name "$ADMIN_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --slot "staging" \
            --docker-custom-image-name "$ACR_LOGIN_SERVER/gtaa-admin:${{ github.sha }}" \
            --docker-registry-server-url "https://$ACR_LOGIN_SERVER" \
            --docker-registry-server-user "$ACR_USERNAME" \
            --docker-registry-server-password "$ACR_PASSWORD"

      - name: Swap staging to production
        run: |
          az webapp deployment slot swap \
            --resource-group "$RESOURCE_GROUP" \
            --name "$ADMIN_NAME" \
            --slot "staging" \
            --target-slot "production"

      - name: Delete staging slot
        run: |
          az webapp deployment slot delete \
            --resource-group "$RESOURCE_GROUP" \
            --name "$ADMIN_NAME" \
            --slot staging
  
  build-and-deploy-frontend:
    name: "Build & Deploy the Frontend"
    runs-on: ubuntu-latest
    needs: prepare-infrastructure
    if: ${{ github.event.inputs.deploy_frontend == 'true' }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ACR_NAME: ${{ vars.AZURE_ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.AZURE_ACR_NAME }}.azurecr.io
      ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      FRONTEND_NAME: ${{ vars.GTAA_PREFIX }}app-uks-frontend
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}"
            }

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Frontend/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-frontend:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/gtaa-frontend:latest

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --name "$FRONTEND_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --slot "staging" \
            --settings \
              ASPNETCORE_ENVIRONMENT="${{ github.event.inputs.environment }}"

      - name: Update Frontend App Service
        run: |
          az webapp config container set \
            --name "$FRONTEND_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --slot "staging" \
            --docker-custom-image-name "$ACR_LOGIN_SERVER/gtaa-frontend:${{ github.sha }}" \
            --docker-registry-server-url "https://$ACR_LOGIN_SERVER" \
            --docker-registry-server-user "$ACR_USERNAME" \
            --docker-registry-server-password "$ACR_PASSWORD"

      - name: Swap staging to production
        run: |
          az webapp deployment slot swap \
            --resource-group "$RESOURCE_GROUP" \
            --name "$FRONTEND_NAME" \
            --slot "staging" \
            --target-slot "production"

      - name: Delete staging slot
        run: |
          az webapp deployment slot delete \
            --resource-group "$RESOURCE_GROUP" \
            --name "$FRONTEND_NAME" \
            --slot staging

