name: Validate - E2E Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        default: "Local"
        options:
          - Local
          - Development
          - Test
          - Production
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'src/e2e/gtaa.e2etests/**'
      - '.github/workflows/validate-apps.yaml'
      - '.github/workflows/validate-e2e.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/e2e/gtaa.e2etests/**'
      - '.github/workflows/validate-apps.yaml'
      - '.github/workflows/validate-e2e.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Playwright Tests
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'Local' }}
    environment: ${{ github.event.inputs.environment || 'Local' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Lowercase the env name and username
        run: echo "ENVIRONMENT_UPPER=${ENVIRONMENT^^}" >>${GITHUB_ENV}

      - name: Run E2E Docker Compose
        id: run
        if: ${{ env.ENVIRONMENT == 'Local' }}
        working-directory: ./src
        env:
          DEFAULT_CONNECTION_STRING: ${{ secrets.DEFAULT_CONNECTION_STRING }}
          SQLSERVER_SA_PASSWORD: ${{ secrets.SQLSERVER_SA_PASSWORD }}
          ASPNETCORE_ENVIRONMENT: "Local"
          AZURE_AD_CLIENT_ID: "123"
          AZURE_AD_TENANT_ID: "456"
          AZURE_AD_CLIENT_SECRET: "789"
          AZURE_AD_INSTANCE: "https://login.microsoftonline.com/"
          AZURE_AD_DOMAIN: "example.onmicrosoft.com"
        run: docker compose -f Infrastructure/compose-e2e-tests.yaml up -d

      - name: Install dependencies
        working-directory: ./src/e2e/gtaa.e2etests
        run: yarn install
      
      #     Temporarily disabled these until work starts on the new frontend and admin projects
      #      - name: Install Playwright Browsers
      #        working-directory: ./src/e2e/gtaa.e2etests
      #        run: yarn playwright install --with-deps

      - name: Run healthcheck
        if: steps.run.outcome == 'success'
        working-directory: ./src/e2e/gtaa.e2etests
        run: |
          echo "Running health project to validate API is up..."
          ${{ env.ENVIRONMENT_UPPER }}_API_URL=${{ vars.QA_API_URL }}
          ${{ env.ENVIRONMENT_UPPER }}_ADMIN_URL=${{ vars.QA_ADMIN_URL }}
          ${{ env.ENVIRONMENT_UPPER }}_FE_URL=${{ vars.QA_FRONTEND_URL }}
            yarn playwright test -c playwright.config.ts --project=health

#     Run only API tests for now
      - name: Run Playwright Api Tests
        if: steps.run.outcome == 'success'
        working-directory: ./src/e2e/gtaa.e2etests
        run: |
          ${{ env.ENVIRONMENT_UPPER }}_API_URL=${{ vars.QA_API_URL }} \
          yarn playwright test -c playwright.config.ts --project=Api
          
#      - name: Run Playwright Admin Tests
#        if: steps.run.outcome == 'success'
#        working-directory: ./src/e2e/gtaa.e2etests
#        run: |
#          ${{ ENVIRONMENT_UPPER }}_ADMIN_URL=${{ vars.QA_ADMIN_URL }} \
#          yarn playwright test -c playwright.config.ts --project=Admin
#          
#      - name: Run Playwright Frontend Tests
#        if: steps.run.outcome == 'success'
#        working-directory: ./src/e2e/gtaa.e2etests
#        run: |
#          ${{ ENVIRONMENT_UPPER }}_FE_URL=${{ vars.QA_FRONTEND_URL }} \
#          yarn playwright test -c playwright.config.ts --project=Frontend

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./src/e2e/gtaa.e2etests/playwright-report/
          if-no-files-found: ignore

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: ./src/e2e/gtaa.e2etests/test-results/screenshots/
